# Generated by Django 4.2.1 on 2023-12-11 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0018_rename_third_high_materail_orderbom_third_high_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spec',
            name='cBOMFile',
        ),
        migrations.CreateModel(
            name='tableBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cBOMFile', models.FileField(blank=True, null=True, upload_to='')),
                ('SpecBOM', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='detailes', to='specapp.spec')),
            ],
        ),
        migrations.AlterField(
            model_name='shipping',
            name='home',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='specapp.tablebom'),
        ),
    ]
