# Generated by Django 4.2.1 on 2023-12-12 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0019_remove_spec_cbomfile_tablebom_alter_shipping_home'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tablebom',
            table='tableBOM',
        ),
    ]
