# Generated by Django 4.2.1 on 2023-12-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0025_orderbom_fiv_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbom',
            name='fourteen_afterasstime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='fourteen_foreignintotime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='fourteen_intotime',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='nine_brand_default',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_brine',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_brineboard',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_brinefins',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_brinepipe_thick',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_brinesize',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_brinethick',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_brinewaterpipe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_cold',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_hot',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_steam',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_steamboard',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_steamfins',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_steampipe_thick',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_steamsize',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_steamthick',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='seven_steamwaterpipe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='ten_motor_brand_default',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='thirteen_displace_default',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='thirteen_fixway_default',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='tweleve_roof',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='twelve_newmaterial',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='twelve_silicone_default',
            field=models.CharField(default='', max_length=20),
        ),
    ]
