# Generated by Django 4.2.1 on 2023-12-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0026_orderbom_fourteen_afterasstime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbom',
            old_name='tweleve_roof',
            new_name='twelve_roof',
        ),
    ]
