# Generated by Django 4.2.1 on 2023-12-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0027_rename_tweleve_roof_orderbom_twelve_roof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbom',
            old_name='televe_material',
            new_name='twelve_material',
        ),
    ]
