# Generated by Django 4.2.1 on 2023-12-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0028_rename_televe_material_orderbom_twelve_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbom',
            name='fourteen_budgetdollar',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='orderbom',
            name='thirteen_budgetdollar',
            field=models.CharField(default='', max_length=20),
        ),
    ]
