# Generated by Django 4.2.1 on 2023-12-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0030_alter_orderbom_third_basic_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbom',
            name='eight_material',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='eight_thick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='eleven_form',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='eleven_key',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='eleven_level',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='eleven_material',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='eleven_size',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fifteen_box',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fifteen_level',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fifteen_location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fifteen_vertical',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='first_boxmaterial',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='first_boxthick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='first_inmaterial',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='first_inother',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='first_inthick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='first_outmaterial',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='first_outthick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fiv_form',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fiv_humidifier',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='four_SSCR',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='four_heater',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='four_material',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='four_way',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fourteen_afterass',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fourteen_afterasstime',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fourteen_ass',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fourteen_budget',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fourteen_budgetdollar',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fourteen_foreigninto',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fourteen_foreignintotime',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fourteen_into',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fourteen_intotime',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='fourteen_time',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='nine_brand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='nine_brand_default',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='nine_form',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='nine_way',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='second_door',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='second_frame',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_board',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_brine',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_brineboard',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_brinefins',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_brinepipe_thick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_brinesize',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_brinethick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_brinewaterpipe',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_cold',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_fins',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_hot',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_hotboard',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_hotfins',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_hotpipe_thick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_hotsize',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_hotthick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_hotwaterpipe',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_other',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_pipe_thick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_size',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_steam',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_steamboard',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_steamfins',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_steampipe_thick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_steamsize',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_steamthick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_steamwaterpipe',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_thick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seven_waterpipe',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seventeen_brand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='seventeen_silicone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='six_axis',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='six_blade_material',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='six_form',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='six_frame_material',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='six_winddoor',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='sixteen_install',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='sixteen_prepare',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='ten_motor_ask',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='ten_motor_brand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='ten_motor_brand_default',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='ten_motor_cold',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='ten_motor_efficient',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='ten_motor_elec',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='ten_motor_form',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='ten_motor_level',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='ten_motor_open',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_basic',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_basic_brand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_basic_efficient',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_basic_install',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_basic_material',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_basic_medium_material',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_basic_thick',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_high',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_high_brand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_high_efficient',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_high_frame',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_high_frameform',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_high_long',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_high_material',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_medium',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_medium_brand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_medium_efficient',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_medium_frame',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_medium_frameform',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='third_medium_long',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_apply',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_box',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_budget',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_budgetdollar',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_displace',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_displace_default',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_elevator',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_fix',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_fixway',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_fixway_default',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_into',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_shocbox',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_shock',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='thirteen_way',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_brand',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_level',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_light',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_light_elec',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_light_open',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_location',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_material',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_net',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_newmaterial',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_pressure',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_roof',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_silicone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_silicone_default',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_test',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_unit',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_view',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderbom',
            name='twelve_winddoor',
            field=models.CharField(default='', max_length=30),
        ),
    ]
