# Generated by Django 4.2.1 on 2024-02-28 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0035_tablespec_alter_shipping_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='chaveorder',
            field=models.CharField(default='無', max_length=50),
        ),
    ]
