# Generated by Django 4.2.1 on 2023-10-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cNumber', models.CharField(default='', max_length=50)),
                ('cProject', models.CharField(max_length=50)),
                ('cName', models.CharField(default='', max_length=50)),
                ('cClient', models.CharField(max_length=50)),
                ('cFile', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'Spec',
            },
        ),
    ]
