# Generated by Django 4.2.1 on 2023-10-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0002_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='cNumber',
            field=models.CharField(default='', max_length=50),
        ),
    ]
