# Generated by Django 4.2.1 on 2023-11-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0003_compare_cnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='spec',
            name='cBOMFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
