# Generated by Django 4.2.1 on 2023-12-10 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0012_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productcount',
        ),
    ]
