# Generated by Django 4.2.1 on 2023-12-11 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0015_spec_chaveorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbom',
            name='third_medium_material',
        ),
    ]
