# Generated by Django 4.2.1 on 2023-12-11 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0016_remove_orderbom_third_medium_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbom',
            name='third_high_material',
        ),
    ]
