# Generated by Django 4.2.1 on 2023-12-12 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0021_remove_spec_chaveorder_tablebom_chaveorder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbom',
            name='home',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='specapp.tablebom'),
        ),
    ]
