# Generated by Django 4.2.1 on 2023-12-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0023_alter_orderbom_cnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productorder',
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(default='', max_length=250),
        ),
    ]
