# Generated by Django 4.2.1 on 2023-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0031_alter_orderbom_eight_material_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbom',
            name='third_basic_medium_material',
            field=models.CharField(default='', max_length=50),
        ),
    ]
