# Generated by Django 4.2.1 on 2024-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0033_special'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbom',
            name='ten_motor_Insulation',
            field=models.CharField(default='', max_length=30),
        ),
    ]
