# Generated by Django 4.2.1 on 2024-04-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0037_remove_shipping_home_remove_tablebom_specbom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablespec',
            name='fifteen_budget',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tablespec',
            name='fifteen_tool',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tablespec',
            name='six_mm',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tablespec',
            name='third_level',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tablespec',
            name='thirteen_shockbox_form',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tablespec',
            name='twelve_mm',
            field=models.CharField(default='', max_length=30),
        ),
    ]
