# Generated by Django 4.2.1 on 2024-04-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specapp', '0038_tablespec_fifteen_budget_tablespec_fifteen_tool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablespec',
            name='fifteen_view',
            field=models.CharField(default='', max_length=30),
        ),
    ]
